### ISSUE TITLE
Crash on Java9 and higher

### ISSUE THREAD

**Issue by linzexin022** [Fox2Code/FabricZero#2] opened 2020-08-06 04:24 UTC
Hi there, I tested your mod in single game, and it just crashed.
Game Version: 1.16.1
Mod Version: 0.1.0

Here's the game log:

[main/ERROR]: Error loading companion plugin class [com.fox2code.fabriczero.FabricZeroPlugin] for mixin config [fabriczero.mixins.json]. The plugin may be out of date: NoClassDefFoundError:Could not initialize class com.fox2code.fabriczero.reflectutils.Java9Fix
java.lang.NoClassDefFoundError: Could not initialize class com.fox2code.fabriczero.reflectutils.Java9Fix
	at com.fox2code.fabriczero.reflectutils.ReflectUtil.forceGet(ReflectUtil.java:59) ~[fabriczero-0.1.0.jar:?]
	at com.fox2code.fabriczero.FabricZeroPlugin.<clinit>(FabricZeroPlugin.java:41) ~[fabriczero-0.1.0.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:427) ~[?:?]
	at net.fabricmc.loader.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:83) ~[fabric-loader-0.9.0+build.204.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:598) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:476) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:438) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.9.0+build.204.jar:0.8+build.18+unknown-b18.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-loader-0.9.0+build.204.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) [?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.0+build.204.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[12:22:46] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
[12:22:46] [main/WARN]: Error loading class: com/thebrokenrail/modupdater/client/gui/ModUpdateScreen (java.lang.ClassNotFoundException: com/thebrokenrail/modupdater/client/gui/ModUpdateScreen)

**Comment by Fox2Code** [comment] 2020-08-06 10:40
Java9 is not fully tested yet and support will comme in a future release

**Comment by Fox2Code** [comment] 2020-08-06 10:44
Duplicate of #1

**Comment by Fox2Code** [comment] 2020-08-06 10:55
I close the issue here but if you want to continue to talk about the problem report it here -> https://github.com/Fox2Code/FabricZero/issues/1  
I prefer if all comments about the same bug are at the same place

**Closed as completed by Fox2Code** 2020-08-06 10:55 UTC
Labels: bug
